'use client';
import Link from '@/components/app-link';
import {useState} from 'react';
import {Heading} from '@/components/study-shell';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
const questions=[{q:'Which structure produces most ATP during aerobic respiration in a typical eukaryotic cell?',options:['Nucleus','Mitochondrion','Ribosome'],correct:'Mitochondrion',explanations:['The nucleus houses most of the cell’s DNA; it is not the main site of ATP production.','Mitochondria produce most ATP during aerobic respiration through oxidative phosphorylation.','Ribosomes assemble proteins; they do not perform oxidative phosphorylation.'],source:'During aerobic respiration, mitochondria generate most cellular ATP through oxidative phosphorylation.',page:1},{q:'What is the main function of a ribosome?',options:['Assembling proteins','Storing genetic information','Controlling entry to the cell'],correct:'Assembling proteins',explanations:['Ribosomes translate messenger RNA into chains of amino acids that form proteins.','Most genetic information is stored in the nucleus in a typical eukaryotic cell.','The plasma membrane regulates movement into and out of the cell.'],source:'Ribosomes translate messenger RNA into polypeptides, which fold into functional proteins.',page:2},{q:'What does selective permeability allow a membrane to do?',options:['Let every substance pass freely','Block every substance','Regulate which substances cross'],correct:'Regulate which substances cross',explanations:['Some substances cross readily, while others need transport proteins or cannot cross.','Cells must exchange selected substances with their surroundings.','Selective permeability controls movement of substances across the membrane.'],source:'The plasma membrane is selectively permeable: its lipid bilayer and transport proteins regulate what enters and leaves the cell.',page:3}];
export default function Quiz(){const [index,setIndex]=useState(0);const [choice,setChoice]=useState('');const [submitted,setSubmitted]=useState(false);const [score,setScore]=useState(0);const [done,setDone]=useState(false);const q=questions[index];return <div className="narrow"><Link className="back" href="/course">← Introduction to Biology</Link><Heading eyebrow="PRACTICE QUIZ · SAMPLE" title={done?'A little practice goes a long way.':'Think it through.'} description="Cell biology essentials · These answers and explanations are prewritten examples."/>{done?<section className="panel"><h2>You scored {score} out of 3</h2><p>This demo result is not saved. Revisit the source excerpts whenever a concept needs another look.</p><div className="actions"><Button onClick={()=>{setIndex(0);setChoice('');setScore(0);setDone(false);setSubmitted(false)}}>Try again</Button><Link href="/flashcards" className="text-link">Review flashcards</Link></div></section>:<section className="panel"><p className="eyebrow">QUESTION {index+1} OF 3</p><Progress value={index/3*100} aria-label="Quiz completed"/><h2 id="question-title" className="my-6">{q.q}</h2><RadioGroup aria-labelledby="question-title" value={choice} onValueChange={v=>setChoice(String(v))} disabled={submitted}>{q.options.map((option,i)=><label key={option} className="option"><RadioGroupItem value={option}/><span>{String.fromCharCode(65+i)}. {option}</span></label>)}</RadioGroup>{submitted&&<output className="feedback block"><strong>{choice===q.correct?'That’s correct.':'Not quite. Let’s unpack it.'}</strong><p>{q.explanations[q.options.indexOf(q.correct)]}</p>{choice!==q.correct&&<p className="mt-2">{q.explanations[q.options.indexOf(choice)]}</p>}<details className="source"><summary>View sample source · Page {q.page}</summary><p>{q.source}</p></details></output>}<div className="actions">{!submitted?<Button disabled={!choice} onClick={()=>{setSubmitted(true);if(choice===q.correct)setScore(s=>s+1)}}>Check answer</Button>:<Button onClick={()=>{if(index===2)setDone(true);else{setIndex(i=>i+1);setChoice('');setSubmitted(false)}}}>{index===2?'See results':'Next question →'}</Button>}</div></section>}</div>}

